[package]
name = "decomp-toolkit"
description = "Yet another GameCube/Wii decompilation toolkit."
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
version = "0.4.0"
edition = "2021"
publish = false
build = "build.rs"
repository = "https://github.com/encounter/decomp-toolkit"
readme = "README.md"
categories = ["command-line-utilities"]

[[bin]]
name = "dtk"
path = "src/main.rs"

[profile.release]
lto = "thin"
panic = "abort"
strip = "debuginfo"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
ar = { git = "https://github.com/bjorn3/rust-ar.git", branch = "write_symbol_table" }
argp = "0.3.0"
base16ct = "0.2.0"
base64 = "0.21.2"
binrw = "0.11.2"
byteorder = "1.4.3"
cwdemangle = "0.1.5"
dol = { git = "https://github.com/encounter/ppc750cl", rev = "5f6e991bf495388c4104f188d2e90c79da9f78de" }
filetime = "0.2.21"
fixedbitset = "0.4.2"
flagset = { version = "0.4.3", features = ["serde"] }
flate2 = "1.0.26"
glob = "0.3.1"
hex = "0.4.3"
indexmap = "2.0.0"
itertools = "0.11.0"
log = "0.4.19"
memchr = "2.5.0"
memmap2 = "0.7.1"
multimap = "0.9.0"
num_enum = "0.6.1"
object = { version = "0.31.1", features = ["read_core", "std", "elf", "write_std"], default-features = false }
once_cell = "1.18.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
path-slash = "0.2.1"
petgraph = "0.6.3"
ppc750cl = { git = "https://github.com/encounter/ppc750cl", rev = "5f6e991bf495388c4104f188d2e90c79da9f78de" }
rayon = "1.7.0"
regex = "1.9.0"
rustc-hash = "1.1.0"
serde = "1.0.166"
serde_json = "1.0.104"
serde_repr = "0.1.14"
serde_yaml = "0.9.22"
sha-1 = "0.10.1"
smallvec = "1.11.0"
tracing = "0.1.37"
tracing-attributes = "0.1.26"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[build-dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
base64 = "0.21.2"
flagset = { version = "0.4.3", features = ["serde"] }
serde = "1.0.166"
serde_repr = "0.1.14"
serde_yaml = "0.9.22"
rmp-serde = "1.1.1"
flate2 = "1.0.26"
