[package]
name = "decomp-toolkit"
description = "GameCube/Wii decompilation project tools."
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
version = "0.1.1"
edition = "2021"
publish = false
build = "build.rs"
repository = "https://github.com/encounter/decomp-toolkit"
readme = "README.md"
categories = ["command-line-utilities"]

[[bin]]
name = "dtk"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.64"
argh = "0.1.8"
base16ct = "0.1.1"
cwdemangle = "0.1.3"
filetime = "0.2.18"
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.17"
memchr = "2.5.0"
memmap2 = "0.5.7"
multimap = "0.8.3"
object = { version = "0.30.0", features = ["read_core", "std", "elf"], default-features = false }
pretty_env_logger = "0.4.0"
regex = "1.6.0"
sha-1 = "0.10.0"
topological-sort = "0.2.2"

[build-dependencies]
anyhow = "1.0.64"
vergen = { version = "7.4.2", features = ["build", "git"], default-features = false }

